# DDS0: J6, DDS1: J7

set_property IOSTANDARD LVCMOS33 [get_ports {AT0_SPI[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT0_SPI[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT0_SPI[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT0_SPI[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT1_SPI[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT1_SPI[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT1_SPI[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AT1_SPI[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports DS0_MARST]
set_property IOSTANDARD LVCMOS33 [get_ports DS0_IORST]
set_property IOSTANDARD LVCMOS33 [get_ports DS0_IOUPD]
set_property IOSTANDARD LVCMOS33 [get_ports DS0_SYNCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DS0_OSK]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_SPI[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_SPI[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_SPI[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_SPI[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PROF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PROF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PROF[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DS0_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports DS0_PDCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_F[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_F[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS0_PD[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports DS1_MARST]
set_property IOSTANDARD LVCMOS33 [get_ports DS1_IORST]
set_property IOSTANDARD LVCMOS33 [get_ports DS1_IOUPD]
set_property IOSTANDARD LVCMOS33 [get_ports DS1_SYNCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DS1_OSK]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_SPI[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_SPI[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_SPI[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_SPI[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PROF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PROF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PROF[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DS1_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports DS1_PDCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_F[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_F[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DS1_PD[0]}]


set_property SLEW SLOW [get_ports {DS0_PROF[2]}]
set_property SLEW SLOW [get_ports {DS0_PROF[1]}]
set_property SLEW SLOW [get_ports {DS0_PROF[0]}]
set_property SLEW SLOW [get_ports DS0_IOUPD]
set_property SLEW SLOW [get_ports {DS0_PD[15]}]
set_property SLEW SLOW [get_ports {DS0_PD[14]}]
set_property SLEW SLOW [get_ports {DS0_PD[13]}]
set_property SLEW SLOW [get_ports {DS0_PD[12]}]
set_property SLEW SLOW [get_ports {DS0_PD[11]}]
set_property SLEW SLOW [get_ports {DS0_PD[10]}]
set_property SLEW SLOW [get_ports {DS0_PD[9]}]
set_property SLEW SLOW [get_ports {DS0_PD[8]}]
set_property SLEW SLOW [get_ports {DS0_PD[7]}]
set_property SLEW SLOW [get_ports {DS0_PD[6]}]
set_property SLEW SLOW [get_ports {DS0_PD[5]}]
set_property SLEW SLOW [get_ports {DS0_PD[4]}]
set_property SLEW SLOW [get_ports {DS0_PD[3]}]
set_property SLEW SLOW [get_ports {DS0_PD[2]}]
set_property SLEW SLOW [get_ports {DS0_PD[1]}]
set_property SLEW SLOW [get_ports {DS0_PD[0]}]

set_property SLEW SLOW [get_ports {DS1_PROF[2]}]
set_property SLEW SLOW [get_ports {DS1_PROF[1]}]
set_property SLEW SLOW [get_ports {DS1_PROF[0]}]
set_property SLEW SLOW [get_ports DS1_IOUPD]
set_property SLEW SLOW [get_ports {DS1_PD[15]}]
set_property SLEW SLOW [get_ports {DS1_PD[14]}]
set_property SLEW SLOW [get_ports {DS1_PD[13]}]
set_property SLEW SLOW [get_ports {DS1_PD[12]}]
set_property SLEW SLOW [get_ports {DS1_PD[11]}]
set_property SLEW SLOW [get_ports {DS1_PD[10]}]
set_property SLEW SLOW [get_ports {DS1_PD[9]}]
set_property SLEW SLOW [get_ports {DS1_PD[8]}]
set_property SLEW SLOW [get_ports {DS1_PD[7]}]
set_property SLEW SLOW [get_ports {DS1_PD[6]}]
set_property SLEW SLOW [get_ports {DS1_PD[5]}]
set_property SLEW SLOW [get_ports {DS1_PD[4]}]
set_property SLEW SLOW [get_ports {DS1_PD[3]}]
set_property SLEW SLOW [get_ports {DS1_PD[2]}]
set_property SLEW SLOW [get_ports {DS1_PD[1]}]
set_property SLEW SLOW [get_ports {DS1_PD[0]}]

# -------------------------------------------------------------

# AT0_SPI[3:0] = {MISO, MOSI, SCLK, CSEL}
set_property PACKAGE_PIN U15 [get_ports {AT0_SPI[0]}]
set_property PACKAGE_PIN V14 [get_ports {AT0_SPI[1]}]
set_property PACKAGE_PIN U16 [get_ports {AT0_SPI[2]}]
set_property PACKAGE_PIN U14 [get_ports {AT0_SPI[3]}]

# AT1_SPI[3:0] = {MISO, MOSI, SCLK, CSEL}
set_property PACKAGE_PIN V17 [get_ports {AT1_SPI[0]}]
set_property PACKAGE_PIN T18 [get_ports {AT1_SPI[1]}]
set_property PACKAGE_PIN T17 [get_ports {AT1_SPI[2]}]
set_property PACKAGE_PIN V16 [get_ports {AT1_SPI[3]}]

# -------------------------------------------------------------

set_property PACKAGE_PIN M26 [get_ports DS0_MARST]
set_property PACKAGE_PIN AC23 [get_ports DS0_IORST]
set_property PACKAGE_PIN M14 [get_ports DS0_IOUPD]

set_property PACKAGE_PIN U22 [get_ports DS0_SYNCLK]
set_property PACKAGE_PIN AE26 [get_ports DS0_OSK]

# DS0_SPI[3:0] = {MISO, MOSI, SCLK, CSEL}
set_property PACKAGE_PIN AF24 [get_ports {DS0_SPI[0]}]
set_property PACKAGE_PIN T24 [get_ports {DS0_SPI[1]}]
set_property PACKAGE_PIN AE25 [get_ports {DS0_SPI[2]}]
set_property PACKAGE_PIN AC22 [get_ports {DS0_SPI[3]}]

set_property PACKAGE_PIN M15 [get_ports {DS0_PROF[0]}]
set_property PACKAGE_PIN L14 [get_ports {DS0_PROF[1]}]
set_property PACKAGE_PIN L15 [get_ports {DS0_PROF[2]}]

set_property PACKAGE_PIN K17 [get_ports DS0_TXEN]
set_property PACKAGE_PIN K21 [get_ports DS0_PDCLK]

set_property PACKAGE_PIN R21 [get_ports {DS0_F[0]}]
set_property PACKAGE_PIN R20 [get_ports {DS0_F[1]}]

set_property PACKAGE_PIN K15 [get_ports {DS0_PD[0]}]
set_property PACKAGE_PIN M16 [get_ports {DS0_PD[1]}]
set_property PACKAGE_PIN L17 [get_ports {DS0_PD[2]}]
set_property PACKAGE_PIN M17 [get_ports {DS0_PD[3]}]
set_property PACKAGE_PIN L18 [get_ports {DS0_PD[4]}]
set_property PACKAGE_PIN K16 [get_ports {DS0_PD[5]}]
set_property PACKAGE_PIN H22 [get_ports {DS0_PD[6]}]
set_property PACKAGE_PIN K20 [get_ports {DS0_PD[7]}]
set_property PACKAGE_PIN K22 [get_ports {DS0_PD[8]}]
set_property PACKAGE_PIN H24 [get_ports {DS0_PD[9]}]
set_property PACKAGE_PIN K18 [get_ports {DS0_PD[10]}]
set_property PACKAGE_PIN J23 [get_ports {DS0_PD[11]}]
set_property PACKAGE_PIN J24 [get_ports {DS0_PD[12]}]
set_property PACKAGE_PIN K23 [get_ports {DS0_PD[13]}]
set_property PACKAGE_PIN J26 [get_ports {DS0_PD[14]}]
set_property PACKAGE_PIN H23 [get_ports {DS0_PD[15]}]

# -------------------------------------------------------------

set_property PACKAGE_PIN J14 [get_ports DS1_MARST]
set_property PACKAGE_PIN T25 [get_ports DS1_IORST]
set_property PACKAGE_PIN G25 [get_ports DS1_IOUPD]

set_property PACKAGE_PIN U21 [get_ports DS1_SYNCLK]
set_property PACKAGE_PIN G22 [get_ports DS1_OSK]

# DS1_SPI[3:0] = {MISO, MOSI, SCLK, CSEL}
set_property PACKAGE_PIN P25 [get_ports {DS1_SPI[0]}]
set_property PACKAGE_PIN R25 [get_ports {DS1_SPI[1]}]
set_property PACKAGE_PIN J21 [get_ports {DS1_SPI[2]}]
set_property PACKAGE_PIN N26 [get_ports {DS1_SPI[3]}]

set_property PACKAGE_PIN J25 [get_ports {DS1_PROF[0]}]
set_property PACKAGE_PIN G26 [get_ports {DS1_PROF[1]}]
set_property PACKAGE_PIN H26 [get_ports {DS1_PROF[2]}]

set_property PACKAGE_PIN E25 [get_ports DS1_TXEN]
set_property PACKAGE_PIN G20 [get_ports DS1_PDCLK]

set_property PACKAGE_PIN F25 [get_ports {DS1_F[0]}]
set_property PACKAGE_PIN F23 [get_ports {DS1_F[1]}]

set_property PACKAGE_PIN F24 [get_ports {DS1_PD[0]}]
set_property PACKAGE_PIN H21 [get_ports {DS1_PD[1]}]
set_property PACKAGE_PIN E26 [get_ports {DS1_PD[2]}]
set_property PACKAGE_PIN G24 [get_ports {DS1_PD[3]}]
set_property PACKAGE_PIN D26 [get_ports {DS1_PD[4]}]
set_property PACKAGE_PIN D25 [get_ports {DS1_PD[5]}]
set_property PACKAGE_PIN F22 [get_ports {DS1_PD[6]}]
set_property PACKAGE_PIN E23 [get_ports {DS1_PD[7]}]
set_property PACKAGE_PIN G21 [get_ports {DS1_PD[8]}]
set_property PACKAGE_PIN J20 [get_ports {DS1_PD[9]}]
set_property PACKAGE_PIN H19 [get_ports {DS1_PD[10]}]
set_property PACKAGE_PIN J19 [get_ports {DS1_PD[11]}]
set_property PACKAGE_PIN H18 [get_ports {DS1_PD[12]}]
set_property PACKAGE_PIN J18 [get_ports {DS1_PD[13]}]
set_property PACKAGE_PIN J16 [get_ports {DS1_PD[14]}]
set_property PACKAGE_PIN J15 [get_ports {DS1_PD[15]}]





