set_property IOSTANDARD LVCMOS33 [get_ports FT_ST]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_AC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT_BC[0]}]

# -------------------------------------------------------------

# FT_ST[1:0] = {nSUSPEND, nPWREN}
set_property PACKAGE_PIN B21 [get_ports {FT_ST[0]}]
set_property PACKAGE_PIN E18 [get_ports {FT_ST[1]}]

set_property PACKAGE_PIN E17 [get_ports {FT_AD[0]}]
set_property PACKAGE_PIN F20 [get_ports {FT_AD[1]}]
set_property PACKAGE_PIN F19 [get_ports {FT_AD[2]}]
set_property PACKAGE_PIN G19 [get_ports {FT_AD[3]}]
set_property PACKAGE_PIN G17 [get_ports {FT_AD[4]}]
set_property PACKAGE_PIN H17 [get_ports {FT_AD[5]}]
set_property PACKAGE_PIN H16 [get_ports {FT_AD[6]}]
set_property PACKAGE_PIN H15 [get_ports {FT_AD[7]}]

set_property PACKAGE_PIN H14 [get_ports {FT_AC[0]}]
set_property PACKAGE_PIN G15 [get_ports {FT_AC[1]}]
set_property PACKAGE_PIN G16 [get_ports {FT_AC[2]}]
set_property PACKAGE_PIN F17 [get_ports {FT_AC[3]}]
set_property PACKAGE_PIN F15 [get_ports {FT_AC[4]}]
set_property PACKAGE_PIN E16 [get_ports {FT_AC[5]}]
set_property PACKAGE_PIN F18 [get_ports {FT_AC[6]}]
set_property PACKAGE_PIN D16 [get_ports {FT_AC[7]}]

set_property PACKAGE_PIN C17 [get_ports {FT_BD[0]}]
set_property PACKAGE_PIN A17 [get_ports {FT_BD[1]}]
set_property PACKAGE_PIN B17 [get_ports {FT_BD[2]}]
set_property PACKAGE_PIN D18 [get_ports {FT_BD[3]}]
set_property PACKAGE_PIN C18 [get_ports {FT_BD[4]}]
set_property PACKAGE_PIN A19 [get_ports {FT_BD[5]}]
set_property PACKAGE_PIN B19 [get_ports {FT_BD[6]}]
set_property PACKAGE_PIN A18 [get_ports {FT_BD[7]}]

set_property PACKAGE_PIN D19 [get_ports {FT_BC[0]}]
set_property PACKAGE_PIN C19 [get_ports {FT_BC[1]}]
set_property PACKAGE_PIN D20 [get_ports {FT_BC[2]}]
set_property PACKAGE_PIN E20 [get_ports {FT_BC[3]}]
set_property PACKAGE_PIN A20 [get_ports {FT_BC[4]}]
set_property PACKAGE_PIN B20 [get_ports {FT_BC[5]}]
set_property PACKAGE_PIN C21 [get_ports {FT_BC[6]}]
set_property PACKAGE_PIN E22 [get_ports {FT_BC[7]}]





